### ISSUE TITLE
-v /usr/bin/docker:/usr/bin/docker not needed for docker_stats_exporter.js

### ISSUE THREAD

**Issue by JosRoseboom** [wywywywy/docker_stats_exporter#2]
When using the docker_stats_exporter from a docker container running on ubuntu 20.04, the container does not start because /usr/bin/docker is not present and the process does not have sufficient rights to create it. Looking in the code, /usr/bin/docker is referred to in Jenkinsfile, but not in docker_stats_exporter.js (only the socket). Removing the volume /usr/bin/docker:/usr/bin/docker made docker_stats_exporter.js run perfectly.

I considered creating a pull request for the README, but I do not really know what the applications of Jenkinsfile are, so I decided to just create this issue to mention it.

I use Grafana to visualize the data exported. I shared the visualization for the container stats of this exporter. Maybe it is useful for someone else as well: https://grafana.com/grafana/dashboards/13331/ 

BTW: thanks for this really useful exporter

**Comment by wywywywy** [comment]
Thanks for the feedback.

You are right `-v /usr/bin/docker:/usr/bin/docker` doesn't seem to be needed.  I'll remove it from the README.

The `Jenkinsfile` is also not needed any more.  It's there because I used to use Jenkins to build and push the Docker image to DockerHub.
